baseURL = "https://edge.docs.radapp.io/"
languageCode = "en-us"
title = "Radius Docs"
theme =  "docsy"

disableFastRender = true

# Ignore sample code
ignoreFiles = ["/code/*"]

# Google Analytics
[services.googleAnalytics]
id = "G-9JR8B6TPF9"

enableGitInfo = true

# Mounts
[module]
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "shared-content"
    target = "content"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "data"
    target = "data"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"

# Taxonomies
[taxonomies]
category = "categories"
tag = "tags"

# Top Nav Bar
[[menu.main]]
    name = "Home"
    weight = 10
    url = "https://radapp.io"
    pre = "<i class='fas fa-home'></i>"
[[menu.main]]
    name = "Blog"
    weight = 20
    url = "https://blog.radapp.io"
    pre = "<i class='fas fa-blog'></i>"
[[menu.main]]
    name = "GitHub"
    weight = 40
    url = "https://github.com/radius-project"
    pre = "<i class='fab fa-github'></i>"
[[menu.main]]
    name = "Discord"
    weight = 90
    url = "https://aka.ms/Radius/Discord"
    pre = "<i class='fab fa-discord'></i>"

[params]
copyright = "The Radius Authors. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see the https://linuxfoundation.org/trademark-usage/ page."
version = "edge"
tag_version = "latest"
chart_version = "0.26.0"

# Algolia Search
algolia_docsearch = true

# GitHub Information
github_repo = "https://github.com/radius-project/docs"
github_subdir = "docs"
github_branch = "edge"
github_project_repo = "https://github.com/radius-project/radius"

# Versioning
version_menu = "Releases"
[[params.versions]]
  version = "edge (preview)"
  url = "https://edge.docs.radapp.io"

[[params.versions]]
  version = "latest"
  url = "https://docs.radapp.io"

# Markdown Engine - Allow inline html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# UI Customization
[params.ui]
sidebar_menu_compact = true
sidebar_search_disable = true
sidebar_menu_foldable = true
sidebar_menu_truncate = 500
ul_show = 1
navbar_logo = true

[params.ui.feedback]
enable = true
yes = '<b>Glad to hear it!</b> Please feel free to <a href="https://github.com/radius-project/radius">star our repo</a> and join our <a href="https://aka.ms/radius/discord">Discord server</a> to stay up to date with the project.'
no = '<b>Sorry to hear that.</b> If you would like to also contribute a suggestion visit <a href="https://github.com/radius-project/docs/issues/new/choose"> and tell us how we can improve</a>.'
